source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'musica' do
  use_frameworks!

  pod 'YoutubePlayer-in-WKWebView', '~> 0.3.0'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SwiftyStoreKit'
  pod 'TransitionableTab'
  pod 'DGElasticPullToRefresh'
  pod 'RAMAnimatedTabBarController'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Instructions'
  pod 'ReachabilitySwift'
  pod 'BubbleTransition'
  pod 'SDWebImage'
  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Crashlytics'
  pod 'SWTableViewCell', '~> 0.3.7'
  pod 'SlideMenuControllerSwift'
  pod 'GoogleMobileAdsMediationMaio'
  pod 'MultiSlider'
  pod 'XCDYouTubeKit', '~> 2.11'
  pod 'SwiftEntryKit', '1.2.3'

  target 'musicaTests' do
    inherit! :search_paths
  end

  target 'musicaUITests' do
    inherit! :search_paths
  end

end
